nome = str(input('Digite seu nome compelto: ')).strip()
print('Analizando seu nome......')
print('Seu nome em maiúsculo é {}'.format(nome.upper()))
print('Seu nome em minúsculo é {}'.format(nome.lower()))
print('Seu nome tem {} de letras'.format(len(nome) - nome.count(' ')))
print('Seu primeio nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))